module.exports = {
    secret:"colorpeach",
    //需要权限访问
    authPath:[
        "edit",
        "org",
        "user",
        "deck"
    ],
    //需要权限ajax访问
    authAjaxPath:[
        "get",
        "post",
        "put",
        "options",
        "head",
        "delete"
    ],
    //不需要权限ajax访问
    unauthAjaxPath:[
        "fetch",
        "mock",
        "mocktpl",
        "photo"
    ],
    //不需要权限访问
    unauthPath:[
        "",
        "login",
        "logout",
        "register",
        "account",
        "slide",
        "doc",
        "tools",
        "projects",
        "demo",
        "modifypassword"
    ],
    //静态文件路径
    staticPath:[
        "js",
        "lib",
        "css",
        "common",
        "utils"
    ]
};
