var icons = [
    "adjust",
    "align-center",
    "align-justify",
    "align-left",
    "arrow-down",
    "arrow-left",
    "arrow-right",
    "arrow-up",
    "asterisk",
    "backward",
    "ban-circle",
    "barcode",
    "bold",
    "bookmark",
    "certificate",
    "check",
    "chevron-down",
    "chevron-left",
    "chevron-right",
    "chevron-up",
    "collapse-down",
    "collapse-up",
    "comment",
    "credit-card",
    "download",
    "eject",
    "expand",
    "facetime-video",
    "fast-backward",
    "fast-forward",
    "file",
    "film",
    "filter",
    "flag",
    "flash",
    "folder-close",
    "folder-open",
    "font",
    "forward",
    "glass",
    "headphones",
    "heart",
    "home",
    "italic",
    "link",
    "list",
    "list1",
    "lock",
    "log-in",
    "magnet",
    "mail",
    "map-marker",
    "minus",
    "ok",
    "ok-circle",
    "ok-sign",
    "open",
    "pause",
    "pencil",
    "phone",
    "play",
    "play-circle",
    "plus",
    "question-sign",
    "record",
    "remove",
    "remove-circle",
    "resize-horizontal",
    "resize-vertical",
    "save",
    "saved",
    "screenshot",
    "signal",
    "star",
    "stats",
    "step-backward",
    "step-forward",
    "stop",
    "tag",
    "tags",
    "tasks",
    "th-large",
    "th-list",
    "time",
    "trash",
    "unchecked",
    "upload",
    "user",
    "wrench",
    "zoom-in",
    "zoom-out"
];

var html = '';
for(var i=0,len=icons.length;i<len;i++){
   html += template(icons[i]);
}

document.querySelector('.box').innerHTML = html;

function template(mark){
    return [
        '<div class="section">',
            '<div class="figure">',
                '<div class="icon">',
                    '<span class="xicon-'+mark+'"></span>',
                '</div>',
                '<div class="figcaption">',
                    '<p>'+mark+'</p>',
                    '<i>.xicon-'+mark+'</i>',
                '</div>',
            '</div>',
        '</div>'
        ].join('');
};